package com.example.passbook.utils;

public class Constant {
    public static String layout = "layout";
    public static String title = "title";
    public static final String CUSTOMER_TABLE = "CUSTOMER_TABLE";
    public static final String BANK_REGULATION_TABLE = "BANK_REGULATION_TABLE";
    public static final String PASSBOOK_REGULATION_TABLE = "PASSBOOK_REGULATION_TABLE";
    public static final String PASSBOOK_TABLE = "PASSBOOK_TABLE";
    public static final String TRANSACTION_FORM_TABLE = "TRANSACTION_FORM_TABLE";
    public static final String SELECT_ALL = "SELECT * FROM ";
    public static final String DELETE_ALL = "DELETE FROM ";
    public static final String WHERE = " WHERE ";
    public static final String LIKE = " LIKE :";
    public static final String LIMIT = " LIMIT ";
    public static final String ID = "Id";
    public static final String IDENTIFY_NUMBER_COLUMN = "identifyNumber";
    public static final String REGISTER_PASSBOOK = "Register Passbook";
    public static final String ADDRESS = "Address";
    public static final String PASSBOOK_ID = "Passbook Id";
    public static final String PASSBOOK_TYPE = "Passbook Type";
    public static final String CUSTOMER_NAME = "Customer Name";
    public static final String CUSTOMER_ID = "Customer Id";
    public static final String IDENTITY_NUMBER = "Identify Number";
    public static final String REGISTER_DATE = "Register Date";
    public static final String AMOUNT = "Amount";
    public static final String THREE_MONTHS = "3 Months";
    public static final String SIX_MONTHS = "6 Months";
    public static final String INFINITE = "Infinite";
    public static final String DEPOSIT_SLIP = "Deposit Slip";
    public static final String DEPOSIT_DATE = "Deposit Date";
    public static final String WITHDRAWAL_SLIP = "Withdrawal Slip";
    public static final String WITHDRAW_DATE = "Withdraw Date";
    public static final String ORDER_BY = " ORDER BY ";
    public static final String DESC = " DESC ";
    public static final String REPORT = "Report";
    public static final String DATE_REPORT = "Date Report";
    public static final String MONTH_REPORT = "Month Report";
    public static final String DATE_TO_GET_REPORT = "DATE_TO_GET_REPORT";
    public static final String CREATION_DATE = "Creation Date";
    public static final String CREATION_DATE_COLUMN = "creationDate";
}
